title: Bronte Baer # your name (or website title) here
logo: "/images/circle-headshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Manager, Data Platforms & Analytics Engineering <br>
  at <a href="https://www.earnest.com/">Earnest</a> 
  <br><br>
  Master's in Data Science <br>
  from <a href="https://ischoolonline.berkeley.edu/data-science/curriculum/">UC Berkeley</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/brontebaer/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
